spring:
 application:
  name: AutomateJobTest
 profiles:
   active: local
logging:
  level:
    org.apache.pulsar: error
    root: info
    ROOT: info
    dev.datainmotion.airquality: info

server.port: 8799